config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :orders ,only: [:success, :create, :new, :show]
  get 'orders/index'

  resources :products do
    collection do
      get 'search'
    end
  end
  
  get 'cart/index'
  resources :cart do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end
  get 'products/index'

  get 'welcome/index'

  devise_for :users

   root 'welcome#index'

  scope module: 'admin' ,as: 'admin', :path =>'admin' do
    root 'welcome#index'
    resources :users, :products
    resources :orders do
      collection do
        get 'setstatus_success'
        get 'setstatus_cancel'
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/orders_controller.rb
module Admin
	class OrdersController < AdminController
		def index
			@orders = Order.where(status: 'pending').order("id DESC").page(params[:page]).per(10)
			@orders1 = Order.where(status: 'success').order("id DESC").page(params[:page]).per(10)
			@orders2 = Order.where(status: 'cancel').order("id DESC").page(params[:page]).per(10)
		end

		def show
			@order = Order.find(params[:id])
		end

		def edit
			@order = Order.find(params[:id])
		end

		def update
			@order = Order.find(params[:id])
			if @order.update(order_params)
				redirect_to admin_orders_path
			else
				render 'edit'
			end
		end

		def setstatus_success
			@order = Order.find(params[:id])
			@order.status = "success"
			if @order.save
				redirect_to :back
			else
				render 'index'
			end

		end

		def setstatus_cancel
			@order = Order.find(params[:id])
			@order.status = "cancel"
			if @order.save
				redirect_to :back
			else
				render 'index'
			end
		end

		private
		def order_params
			params.require(:order).permit(:status)
		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
  end

  def show
    @order = Order.where(user_id: current_user.id).order("id DESC").page(params[:page]).per(10)
  end

  def new
    
  end

  def success

  end
  
  #function checkout
  def create

  	@order = Order.new(order_params)
  	@order.user_id = current_user.id
  	@order.status = "pending"
  	#od = params[:order]
  	#dt = od['reciverdate']
  	
  	#formatted_date = dt.Date.strptime("12/13/2013", "%m/%d/%Y")
  	#@order.reciverdate = formatted_date

  	if @order.save
  		#insert order details
  		
  		session["cart"].each do |h|
        #create orderdetails
  			@orderdetail = Orderdetail.new
  			@orderdetail.order_id = Order.maximum("id")
  			@orderdetail.productname = h['name']
  			@orderdetail.quantity = h['quantity']
        @orderdetail.price = h['price']
        @orderdetail.price_total = h['total']
  			@orderdetail.save
  		end
  		session["cart"] = []
  		render 'success'

  	else
  		render 'index'
  	end

  end

  private

  def order_params
  	params.require(:order).permit(:reciverdate, :reciveraddress, :email, :total, :phone)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/edit.html.erb
<%=form_for :order, url: admin_order_path(@order), method: :patch do |f|%>
	<div class="form-group">
    	<label for="exampleInputEmail1">Date</label>
    	<%=f.text_field :reciverdate, :class=>'form-control', :placeholder=>'Enter you product name'%>
  	</div>

  	<div class="form-group">
    	<label for="exampleInputEmail1">Status</label>
    	<%=f.text_field :status, :class=>'form-control', :placeholder=>'Enter you product name'%>
  	</div>
  	<div class="button-submit form-group">
  		<%=f.submit 'Update Order', :class=>'btn btn-primary' %>
      <button type="reset" class="btn btn-danger">Reset</button>
  	</div>
<%end%>

app/views/admin/orders/index.html.erb
<div class="page-header">
	<h2>Orders Manager</h2>
</div>

<!-- tabs -->

<div class="main">
  
		  <input id="tab1" type="radio" name="tabs" checked>
		  <label id="tab11" for="tab1">Pending</label>
	
		  <input id="tab2" type="radio" name="tabs">
		  <label id="tab22" for="tab2">Success</label>
	
		  <input id="tab3" type="radio" name="tabs">
		  <label id="tab33" for="tab3">Cancel</label>
	
		  
	
		  <div class="content">  
			  <div id="content1">
				<table class="table table-bordered">
					<tr>
						<th>Name</th>
						<th>ReciverDate</th>
						<th>ReciverAddress</th>
						<th>Email</th>
						<th>Phone</th>
						<th>Total</th>
						<th>Created_at</th>
						<th>Success / Cancel / Show</th>
						
					</tr>
					<%@orders.each do |pending|%>
						<tr>
							<td>
								<% us = User.find(pending.user_id) %>
								<%=us.fullname %>
							</td>
							<td><%=pending.reciverdate.strftime('%d-%m-%y')%></td>
							<td><%=pending.reciveraddress%></td>
							<td><%=pending.email%></td>
							<td><%=pending.phone%></td>
							<td><%=number_to_currency(pending.total)%></td>
							<td><%=pending.created_at.strftime('%d-%m-%y %H:%M:%S')%></td>
							<td style="padding-left:50px;">
								<form style="width:30px; float:left" action="/admin/orders/setstatus_success" method="get">
									<input type="hidden" name="id" value='<%=pending.id%>'>
									<button style="font-size:24px; background:none; border:none" type="submit" class="glyphicon glyphicon-ok-circle"></button>
								</form>
								<form style="width:30px; float:left" action="/admin/orders/setstatus_cancel" method="get">
									<input type="hidden" name="id" value='<%=pending.id%>'>
									<button style="font-size:24px; background:none; border:none" type="submit" class="glyphicon glyphicon-remove-circle"></button>
								</form>
								<%=link_to '', admin_order_path(pending),style: "font-size:24px;border:none; float:left; padding-left:6px;color:#000", class: "icon glyphicon glyphicon-share" %>
							</td>
						</tr>
					<%end%>
				</table>
				<%= paginate @orders %>
			  </div>
	
			  <div id="content2">
				<table class="table table-bordered">
					<tr>
						<th>Name</th>
						<th>ReciverDate</th>
						<th>ReciverAddress</th>
						<th>Email</th>
						<th>Phone</th>
						<th>Total</th>
						<th>Status</th>
						<th>Created_at</th>
						<th></th>
						
						
					</tr>
					<%@orders1.each do |success|%>
						<tr>
							<td>
								<% us = User.find(success.user_id) %>
								<%=us.fullname %>
							</td>
							<td><%=success.reciverdate.strftime('%d-%m-%y')%></td>
							<td><%=success.reciveraddress%></td>
							<td><%=success.email%></td>
							<td><%=success.phone%></td>
							<td><%=number_to_currency(success.total)%></td>
							<td><span class="btn btn-primary"><%=success.status%></span></td>
							<td><%=success.created_at.strftime('%d-%m-%y %H:%M:%S')%></td>
							<td><%=link_to '', admin_order_path(success),style: "font-size:24px; float:left; padding-left:6px;color:#000", class: "glyphicon glyphicon-share" %></td>
							
						</tr>
					<%end%>
				</table>
				<%= paginate @orders1 %>
			  </div>
	
			  <div id="content3">
				<table class="table table-bordered">
					<tr>
						<th>Name</th>
						<th>ReciverDate</th>
						<th>ReciverAddress</th>
						<th>Email</th>
						<th>Phone</th>
						<th>Total</th>
						<th>Status</th>
						<th>Created_at</th>
						<th></th>
						
					</tr>
					<%@orders2.each do |cancel|%>
						<tr>
							<td>
								<% us = User.find(cancel.user_id) %>
								<%=us.fullname %>
							</td>
							<td><%=cancel.reciverdate.strftime('%d-%m-%y')%></td>
							<td><%=cancel.reciveraddress%></td>
							<td><%=cancel.email%></td>
							<td><%=cancel.phone%></td>
							<td><%=number_to_currency(cancel.total)%></td>
							<td><span class="btn btn-danger"><%=cancel.status%></span></td>
							<td><%=cancel.created_at.strftime('%d-%m-%y %H:%M:%S')%></td>
							<td><%=link_to '', admin_order_path(cancel),style: "font-size:24px; float:left; padding-left:6px;color:#000", class: "glyphicon glyphicon-share" %></td>
							
						</tr>
					<%end%>
				</table>
				<%= paginate @orders2 %>
			  </div>
	
			  
	
</div>

<style type="text/css">
	table th{
		text-align: center;
	}
	table td{
		text-align: center;
		vertical-align: middle !important;
	}
</style>

app/views/admin/orders/new.html.erb
<div class="main">
  
		  <input id="tab1" type="radio" name="tabs" checked>
		  <label for="tab1">New York</label>
	
		  <input id="tab2" type="radio" name="tabs">
		  <label for="tab2">London</label>
	
		  <input id="tab3" type="radio" name="tabs">
		  <label for="tab3">Mumbai</label>
	
		  <input id="tab4" type="radio" name="tabs">
		  <label for="tab4">Tokyo</label>
	
		  <div class="content">  
			  <div id="content1">
				<p>
				  New York – referred to as New York City or the City of New York to distinguish it from the State of New York, of which it is a part – is the most populous city in the United States and the center of the New York metropolitan area, the premier gateway for legal immigration to the United States and one of the most populous urban agglomerations in the world. A global power city, New York exerts a significant impact upon commerce, finance, media, art, fashion, research, technology, education, and entertainment.
				<p>
				  Home to the headquarters of the United Nations, New York is an important center for international diplomacy and has been described as the cultural and financial capital of the world.
				</p>
			  </div>
	
			  <div id="content2">
				<p>
				 London is the capital city of England and the United Kingdom. It is the most populous city in the United Kingdom, with a metropolitan area of over 13 million inhabitants. Standing on the River Thames, London has been a major settlement for two millennia, its history going back to its founding by the Romans, who named it Londinium.
				</p>
				<p>
				  London's ancient core, the City of London, largely retains its 1.12-square-mile (2.9 km2) mediaeval boundaries and in 2011 had a resident population of 7,375, making it the smallest city in England. Since at least the 19th century, the term London has also referred to the metropolis developed around this core.
				</p>
			  </div>
	
			  <div id="content3">
				<p>
				  Mumbai is the capital city of the Indian state of Maharashtra. It is the most populous city in India, most populous metropolitan area in India, and the eighth most populous city in the world, with an estimated city population of 18.4 million and metropolitan area population of 20.7 million as of 2011. Along with the urban areas, including the cities of Navi Mumbai, Thane, Bhiwandi, Kalyan, it is one of the most populous urban regions in the world.
				</p>
				<p>
				  Mumbai lies on the west coast of India and has a deep natural harbour. In 2009, Mumbai was named an alpha world city. It is also the wealthiest city in India, and has the highest GDP of any city in South, West or Central Asia.
				</p>
			  </div>
	
			  <div id="content4">
				<p>
				 Tokyo, officially Tokyo Metropolis, is one of the 47 prefectures of Japan. Tokyo is the capital of Japan, the center of the Greater Tokyo Area, and the most populous metropolitan area in the world. It is the seat of the Japanese government and the Imperial Palace, and the home of the Japanese Imperial Family.
				</p>
				<p>
				 Tokyo is in the Kantō region on the southeastern side of the main island Honshu and includes the Izu Islands and Ogasawara Islands. Tokyo Metropolis was formed in 1943 from the merger of the former Tokyo Prefecture and the city of Tokyo.
				</p>
			  </div>
		  </div>
	
</div>

app/views/admin/orders/show.html.erb
<div class="page-header">
	<h2>Orders Details</h2>
</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-md-4">
			<p class="lable-p">Custommer Name</p>
			<p class="lable-p">ReciverDate</p>
			<p class="lable-p">ReciverAddress</p>
			<p class="lable-p">Email</p>
			<p class="lable-p">Phone</p>
			<p class="lable-p">Total</p>
			<p class="lable-p">Created_at</p>
			<p class="lable-p">Status</p>
		</div>
		<div class="col-xs-6 col-md-8">
			<p class="lable-data">
			<%
				usr = User.find(@order.user_id)
			%>
			<%=usr.fullname%>
			</p>
			<p class="lable-data"><%=@order.reciverdate.strftime('%d-%m-%Y')%></p>
			<p class="lable-data"><%=@order.reciveraddress%></p>
			<p class="lable-data"><%=@order.email%></p>
			<p class="lable-data"><%=@order.phone%></p>
			<p class="lable-data"><%=number_to_currency(@order.total)%></p>
			<p class="lable-data"><%=@order.created_at.strftime('%d-%m-%Y %H:%M:%S')%></p>
			<p class="lable-data"><span style="margin-top:-11px;" class="btn btn-primary"><%=@order.status%></span></p>
		</div>
	</div>
</div>

<div class="page-header">
	<h2>Product Information</h2>
</div>

<table class="table table-bordered">
	<tr>
		<th>STT</th>
		<th>Product Name</th>
		<th>Quantity</th>
		<th>Price</th>
		<th>Total</th>
	</tr>
	<% ord = Orderdetail.where(order_id: @order.id) %>
	<% i = 0 %>
	
	<% ord.each do |p| %>
		<tr>
			<td><%= (i = i +1 ) %></td>
			<td><%= p.productname %></td>
			<td><%= p.quantity %></td>
			<td><%= number_to_currency(p.price) %></td>
			<td><%= number_to_currency(p.price_total) %></td>
		</tr>
	<%end%>

</table>