config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :orders ,only: [:success, :create, :new, :show]
  get 'orders/index'

  resources :products do
    collection do
      get 'search'
    end
  end
  
  get 'cart/index'
  resources :cart do
    collection do
      get 'add_to_cart'
      get 'update_quantity_to_cart'
      get 'delete_product_to_cart'
    end
  end
  get 'products/index'

  get 'welcome/index'

  devise_for :users

   root 'welcome#index'

  scope module: 'admin' ,as: 'admin', :path =>'admin' do
    root 'welcome#index'
    resources :users, :products
    resources :orders do
      collection do
        get 'setstatus_success'
        get 'setstatus_cancel'
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo,
                    :styles => { :thumb_small => "70x70#",:medium => "480x320#", :thumb => "100x100#", :small => "320x240#", :large => "640x480#" },
                    :default_url => "/images/:style/missing.png",
                    :url => "/images/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/images/products/:id/:style/:basename.:extension"
  
    validates_attachment :photo, content_type: {content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}

    #config for search
    def self.search(query)
    	where("title like ?", "%#{query}%")
    end
end

app/controllers/admin/products_controller.rb
module Admin
	class ProductsController < AdminController
		
		def index
			@products = Product.order("id DESC").page(params[:page]).per(10)
		end

		def show
			@product = Product.find(params[:id])
		end

		def new
			@product = Product.new
		end

		def edit
			@product = Product.find(params[:id])
		end

		def create
			@product = Product.new(product_params)
			if @product.save
				redirect_to admin_products_path
			else
				render 'new'
			end
		end

		def update
			@product = Product.find(params[:id])
			if @product.update(product_params)
				redirect_to admin_products_path
			else
				render 'edit'
			end
		end

		def destroy
			@product = Product.find(params[:id])
			@product.destroy
			redirect_to admin_products_path
		end
		
		private
		def product_params
			params.require(:product).permit(:title, :des, :price, :quantity, :photo)
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.order("id DESC").page(params[:page]).per(9)
  end

  def show
  	@product = Product.find(params[:id])
  end

  #function search by name
  def search
  	@search = Product.search(params[:q]).page(params[:page]).per(12).order("created_at DESC")
    
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="page-header">
  <h2>Edit product <a href="/admin/products" class="btn btn-primary" style="float:right">Back</a></h2>

</div>
<%=form_for  :product, url: admin_product_path(@product), method: :patch do |f|%>
	<div class="form-group">
    	<label for="exampleInputEmail1">Product name</label>
    	<%=f.text_field :title, :class=>'form-control', :placeholder=>'Enter you product name'%>
  	</div>

  	<div class="form-group">
    	<label for="exampleInputPassword">Description</label>
    	<%=f.text_area :des, :class=>'form-control', :placeholder=>'Enter you product description', :style=>'height:120px;'%>
  	</div>

    <div class="form-group">
      <label for="exampleInputFullName">Price</label>
       <div class="input-group">
        <div class="input-group-addon">$</div>
        <%=f.text_field :price, :class=>'form-control', :placeholder=>'Enter you product price'%>
      </div>
    </div>

    <div class="form-group">
      <label for="exampleInputFullName">Quantity</label>
      <%=f.text_field :quantity, :class=>'form-control', :placeholder=>'Enter you product quantity'%>
    </div>

    <div class="form-group">
      <label for="exampleInputFullName">Product Image</label>
      <%=f.file_field :photo%>
      <img id="image_preview" src='<%= @product.photo.url(:small) %>' alt="your image" style="margin-top:10px; width:200px;" />
    </div>

    
  	<div class="button-submit form-group">
  		<%=f.submit 'Update Product', :class=>'btn btn-primary' %>
      <button type="reset" class="btn btn-danger">Reset</button>
  	</div>
<%end%>


<script>
  function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#image_preview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
  }

  $("#product_photo").change(function(){
      readURL(this);
  });
</script>

app/views/admin/products/index.html.erb
<div class="page-header">
	<h2>Products <a href="/admin/products/new" class="btn btn-primary" style="float:right">Add new product</a></h2>

</div>
<table class="table table-bordered">
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Description</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Image</th>
		<th></th>
	</tr>
	<% @products.each do |u| %>
		<tr>
			<td><%= u.id%></td>
			<td><%= u.title%></td>
			<td><%= u.des%></td>
			<td><%= number_to_currency(u.price) %></td>
			<td><%= u.quantity%></td>
			<td><%=image_tag u.photo.url(:thumb_small) %></td>
			<td style="width:170px;">
				<a href='<%=admin_product_path(u) %>' class="icon glyphicon glyphicon-share" alt="Show details user"></a> 
				<a href='<%=edit_admin_product_path(u)%>' class="icon glyphicon glyphicon-edit"></a> 
				<%= link_to '', admin_product_path(u),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'icon glyphicon glyphicon-remove-circle', style: "border-right:none" %>
			</td>
		</tr>
	<%end%>
</table>
<%= paginate @products %>
<style type="text/css">
	table th{
		text-align: center;
	}
	table td{
		text-align: center;
		vertical-align: middle !important;
	}
</style>

app/views/admin/products/new.html.erb
<div class="page-header">
  <h2>New product <a href="/admin/products" class="btn btn-primary" style="float:right">Back</a></h2>

</div>
<%=form_for  :product, url: admin_products_path do |f|%>
	<div class="form-group">
    	<label for="exampleInputEmail1">Product name</label>
    	<%=f.text_field :title, :class=>'form-control', :placeholder=>'Enter you product name'%>
  	</div>

  	<div class="form-group">
    	<label for="exampleInputPassword">Description</label>
    	<%=f.text_area :des, :class=>'form-control', :placeholder=>'Enter you product description', :style=>'height:120px;'%>
  	</div>

    <div class="form-group">
      <label for="exampleInputFullName">Price</label>
      <div class="input-group">
        <div class="input-group-addon">$</div>
        <%=f.text_field :price, :class=>'form-control', :placeholder=>'Enter you product price'%>
      </div>
    </div>

    <div class="form-group">
      <label for="exampleInputFullName">Quantity</label>
      <%=f.text_field :quantity, :class=>'form-control', :placeholder=>'Enter you product quantity'%>
    </div>
    <div class="form-group">
      <label for="exampleInputFullName">Product Image</label>
      <%=f.file_field :photo%>
      <img id="image_preview" src="#" alt="your image" />
    </div>
    
  	<div class="button-submit form-group">
  		<%=f.submit 'Create Product', :class=>'btn btn-primary' %>
      <button type="reset" class="btn btn-danger">Reset</button>
  	</div>
<%end%>
<style type="text/css">
  #image_preview{
    display:none;
  }
</style>
<script>
  function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#image_preview').attr('src', e.target.result);
            $('#image_preview').attr('style', 'display:block; margin-top:10px; width:200px;')
        }

        reader.readAsDataURL(input.files[0]);
    }
  }

  $("#product_photo").change(function(){
      readURL(this);
  });
</script>

app/views/admin/products/show.html.erb
<div class="page-header">
  <h2>Details product <a href="/admin/products" class="btn btn-primary" style="float:right">Back</a></h2>

</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-md-4">
			<p class="lable-p">Product Name</p>
			<p class="lable-p">Description</p>
			<p class="lable-p">Price</p>
			<p class="lable-p">Quantity</p>
			<p class="lable-p" style="height:251px">Image</p>
		</div>
		<div class="col-xs-6 col-md-4">
			<p class="lable-data"><%= @product.title %></p>
			<p class="lable-data"><%= @product.des %></p>
			<p class="lable-data"><%= number_to_currency(@product.price) %></p>
			<p class="lable-data"><%= @product.quantity %></p>
			<p class="lable-data"><%= image_tag @product.photo.url(:small)%></p>
		</div>
	</div>
</div>